### ISSUE TITLE
crashing when upgrading PyJWT beyond 1.7.1

### ISSUE THREAD

**Issue by rchogan** [microsoft/asconnect#19]
When I upgrade PyJWT to a more recent version, I get a crash in httpclient.py, line 138.  It seems that the encode method now returns a string?   

Is there something Im missing?  this project says that it supports PyJWT < 3.0

**Comment by guojiubo** [comment]
I think we're using PyJWT 2.4.0, see the [poetry.lock](https://github.com/microsoft/asconnect/blob/507e284883a3a791182ec4fbb8a519d6ab0da699/poetry.lock#L565) file. And looks like the `encode` method always returns a string, I checked version 1.7.0 and 2.4.0, could you double check?

**Comment by rchogan** [comment]
Hi @guojiubo, thanks for the reply...  Yes, it always returns a string, but on line 138 of httpclient.py, it calls decode on the result of encode, and crashes because it's a str and does not have decode method.

**Comment by dalemyers** [comment]
@guijiubo That lock file is just used for development of asconnect. Anyone using it is free to get anything matching `>=1.7,<3.0`. It looks like the behavior changed in version 2.0 to return a string rather than bytes. So we shouldn't call decode in that case.
